name: flutter_ltdddoan
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
   
  cupertino_icons: ^1.0.6
  badges: ^3.1.2
  intl: ^0.19.0
  shared_preferences: ^2.1.0
  sidebarx: ^0.17.1
  flutter_datetime_picker: ^1.5.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2
  image_picker: ^1.1.0
  photo_view: ^0.15.0
  url_launcher: ^6.2.6
  firebase_app_check: ^0.2.2+2
  provider: ^6.1.2
  carousel_slider: ^4.2.1
  dvhcvn: ^2.0.20240501
  get: ^4.6.6
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_gen_runner: ^5.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/images/
    - assets/icons/
